# Generated by Django 3.2.7 on 2021-09-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('ended_at', models.DateTimeField()),
                ('available', models.IntegerField(default=999)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productoption',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
