# Generated by Django 3.2.7 on 2021-09-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210902_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='available',
        ),
        migrations.AlterField(
            model_name='popup',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
