# Generated by Django 3.2.7 on 2021-09-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='height',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='width',
        ),
    ]
