# Generated by Django 3.2.7 on 2021-09-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210902_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
