# Generated by Django 3.2.7 on 2021-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='option',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
