# Generated by Django 3.2.7 on 2021-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_deliverycompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
